### ISSUE TITLE
Django guardian data migration is failing under certain conditions

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1144]
I tried to run the migrations in a clean database and the data migration which is handling the port of permissions from django-authority to django-guardian was failing because Permissions were not present. I had to use: `./manage.py migrate forums 003 --fake` followed by `./manage.py migrate` and then migrate back to forums `002` and re-run the migrate command.

The error from the migrate command:
```
Operations to perform:
  Apply all migrations: actstream, admin, announcements, auth, authority, authtoken, contenttypes, customercare, dashboards, flagit, forums, gallery, groups, guardian, inproduct, journal, karma, kbadge, kbforums, kitsune_messages, kpi, notifications, postcrash, product_details, products, questions, search, sessions, sites, sumo, taggit, tidings, upload, users, waffle, wiki
Running migrations:
  Applying forums.0003_authority_to_guardian_data...Traceback (most recent call last):
  File "/app/./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/venv/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/venv/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/venv/lib/python3.10/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/venv/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/venv/lib/python3.10/site-packages/django/db/migrations/migration.py", line 123, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/venv/lib/python3.10/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/app/kitsune/forums/migrations/0003_authority_to_guardian_data.py", line 67, in migrate_authority_to_guardian
    assign_perm(
  File "/venv/lib/python3.10/site-packages/guardian/shortcuts.py", line 135, in assign_perm
    return model.objects.assign_perm(perm, group, obj)
  File "/venv/lib/python3.10/site-packages/guardian/managers.py", line 39, in assign_perm
    permission = Permission.objects.get(content_type=ctype, codename=perm)
  File "/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/venv/lib/python3.10/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.Permission.DoesNotExist: Permission matching query does not exist.
```

**Comment by escattone** [comment]
🤦 Ugh, I've only just realized that the permissions in `kitsune/forums/migrations/0002_auto_20221031_0956.py` are created by a `post_migrate` signal handler, so only **after** all of the migrations have been run.

**Comment by mirunacurtean** [comment]
Noticed no issues doung exploratory testing in stage. Navigated through about all menus in sumo.
