### ISSUE TITLE
[Postgres][Dev] fix_current_revisions management command fails

### ISSUE THREAD

**Issue by escattone** [mozilla/sumo#1455]
```python
Traceback (most recent call last):
  File "/app/./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/venv/lib/python3.11/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/venv/lib/python3.11/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/kitsune/wiki/management/commands/fix_current_revisions.py", line 23, in handle
    doc.save()
  File "/app/kitsune/wiki/models.py", line 336, in save
    self._clean_template_status()
  File "/app/kitsune/wiki/models.py", line 260, in _clean_template_status
    raise ValidationError(
django.core.exceptions.ValidationError: ['Documents in the Template category must have titles that start with "Template:". (Current title is "template:JakOtevřítSložkuProfiluvThunderbirdu")']
```

**Comment by escattone** [comment]
Closing this, since this is a legitimate validation error that also occurs in stage and production.

**Comment by escattone** [comment]
This is due to the fact that Postgres sorts `NULL`'s differently than MySQL.

**Comment by escattone** [comment]
[Fixed](https://github.com/mozilla/kitsune/pull/5609/commits/46d6f689b55e410b2ce853c379c3d814f8b94562) in the `switch-to-postgres` branch and manually confirmed.
