### ISSUE TITLE
Indeterminate circleci test failures

### ISSUE THREAD

**Issue by smithellis** [mozilla/sumo#1479]
We recently had an issue with https://github.com/mozilla/kitsune/pull/5533 failing a test in circleci.  The test couldn't be replicated locally and was resolved upon re-running tests. I'm opening this issue to track and analyze if we have further problems with this particular test or see other test failures that are comparable.

This particular failure was https://app.circleci.com/pipelines/github/mozilla/kitsune/3199/workflows/19298706-1c54-4af3-bcfd-5bf215ff909f/jobs/7624, and the error it threw was:

```
FAIL: test_draft_revision_discarded_when_submitting_revision (kitsune.wiki.tests.test_views.DocumentEditingTests.test_draft_revision_discarded_when_submitting_revision)
Check draft revision is discarded when submitting a revision
```

**Comment by escattone** [comment]
Another one:
```
======================================================================
FAIL: test_skip_unready_when_not_first_translation (kitsune.wiki.tests.test_templates.TranslateTests.test_skip_unready_when_not_first_translation)
Never offer an unready-for-localization revision as diff text when
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/kitsune/wiki/tests/test_templates.py", line 2271, in test_skip_unready_when_not_first_translation
    self.assertEqual(200, response.status_code)
AssertionError: 200 != 404

----------------------------------------------------------------------
Ran 1763 tests in 285.169s

FAILED (failures=1, skipped=1)
```

**Comment by escattone** [comment]
```
======================================================================
FAIL: test_query_old (kitsune.users.tests.test_api.UsernamesTests.test_query_old)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/kitsune/users/tests/test_api.py", line 41, in test_query_old
    self.assertEqual(0, len(data))
AssertionError: 0 != 1

```

**Comment by emilghittasv** [comment]
Another example:

https://app.circleci.com/pipelines/github/mozilla/kitsune/4247/workflows/1743a79c-8770-465e-98d8-4ebef038b5a6/jobs/9800

```
FAIL: test_answers_limit (kitsune.questions.tests.test_views.TestRateLimiting.test_answers_limit)
Only four answers per minute can be posted.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/kitsune/questions/tests/test_views.py", line 536, in test_answers_limit
    self.assertEqual(4, Answer.objects.count())
AssertionError: 4 != 7
```

**Comment by escattone** [comment]
```
FAIL: test_draft_revision_restore_in_translation_page (kitsune.wiki.tests.test_views.DocumentEditingTests.test_draft_revision_restore_in_translation_page)
Check Draft Revision is restored when a user click on the Restore Button
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/kitsune/wiki/tests/test_views.py", line 1854, in test_draft_revision_restore_in_translation_page
    self.assertEqual(200, restore_draft_resp.status_code)
AssertionError: 200 != 404
```

**Comment by escattone** [comment]
```
FAIL: test_restore_draft_revision (kitsune.wiki.tests.test_templates.NewRevisionTests.test_restore_draft_revision)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/kitsune/wiki/tests/test_templates.py", line 1110, in test_restore_draft_revision
    self.assertEqual(1, len(trans_content(".user-messages .mzp-c-notification-bar")))
AssertionError: 1 != 0
```

**Comment by escattone** [comment]
```
FAIL: test_trans_lock_workflow (kitsune.wiki.tests.test_views.TestDocumentLocking.test_trans_lock_workflow)
End to end test of locking on a translated document.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/kitsune/wiki/tests/test_views.py", line 2149, in test_trans_lock_workflow
    self._lock_workflow(trans_doc, edit_url)
  File "/app/kitsune/wiki/tests/test_views.py", line 2104, in _lock_workflow
    assert_not_locked(r)
  File "/app/kitsune/wiki/tests/test_views.py", line 2093, in assert_not_locked
    self.assertNotContains(r, 'id="unlock-button"')
  File "/venv/lib/python3.11/site-packages/django/test/testcases.py", line 672, in assertNotContains
    text_repr, real_count, msg_prefix = self._assert_contains(
                                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/django/test/testcases.py", line 610, in _assert_contains
    self.assertEqual(
AssertionError: 404 != 200 : Couldn't retrieve content: Response code was 404 (expected 200)
```

**Comment by escattone** [comment]
```
FAIL: test_discard_draft_revision (kitsune.wiki.tests.test_views.DocumentEditingTests.test_discard_draft_revision)
Check Draft Revision is discarded
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/kitsune/wiki/tests/test_views.py", line 1870, in test_discard_draft_revision
    self.assertEqual(302, restore_draft_resp.status_code)
AssertionError: 302 != 404
```

**Comment by akatsoulas** [comment]
Closing this issue as there are no immediate plans to work on it as part of our regular backlog curation process. If this ticket becomes a priority or requires immediate attention, please feel free to reopen it.
